function initializeRepository(){
  const input=document.querySelector('#repositoryInput');
  if(!input)return;
  const status=document.querySelector('#repositoryStatus'),filesList=document.querySelector('#repositoryFiles'),scanButton=document.querySelector('#scanButton'),scopeTitle=document.querySelector('#scopeTitle'),results=document.querySelector('#scanResults'),findingList=document.querySelector('#findingList'),findingTitle=document.querySelector('#findingTitle');
  const supported=/\.(?:js|jsx|ts|tsx|mjs|cjs|py|java|go|rb|php|cs|rs|sql|html|css)$/i;
  let files=[];
  const rules=[
    {id:'role-input',severity:'Elevated',pattern:/request\s*\.\s*body\s*\.\s*role|body\s*\.\s*role/i,title:'Role selection uses request input',fix:'Resolve authorization roles from a verified server session or database record.'},
    {id:'unsafe-html',severity:'Elevated',pattern:/\.innerHTML\s*=|dangerouslySetInnerHTML/i,title:'Untrusted markup may reach HTML rendering',fix:'Use text content or sanitize the value with a trusted allow list.'},
    {id:'dynamic-execution',severity:'Elevated',pattern:/\beval\s*\(|new\s+Function\s*\(/i,title:'Dynamic code execution detected',fix:'Replace dynamic execution with explicit, validated program logic.'},
    {id:'shell-execution',severity:'Needs review',pattern:/child_process|exec\s*\(|spawn\s*\(/i,title:'Shell execution requires input boundary review',fix:'Use fixed command arguments and never concatenate untrusted input.'},
    {id:'hardcoded-secret',severity:'Needs review',pattern:/(?:api[_-]?key|secret|password)\s*[:=]\s*['"][^'"]{8,}/i,title:'Possible hardcoded secret',fix:'Move credentials to environment variables or a managed secret store.'}
  ];
  const escape=(value)=>value.replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  input.addEventListener('change',()=>{files=[...input.files].filter((file)=>supported.test(file.name)).slice(0,120);const root=input.files[0]?.webkitRelativePath.split('/')[0]||'Selected folder';status.textContent=`${files.length} supported source files selected from ${root}.`;scopeTitle.textContent=`${files.length} files ready for local inspection.`;scanButton.disabled=!files.length;filesList.innerHTML=files.slice(0,16).map((file)=>`<div class="reviewRow"><span class="reviewIcon cyan">⌘</span><div><b>${escape(file.webkitRelativePath||file.name)}</b><small>${Math.ceil(file.size/1024)} KB · read locally</small></div><span class="riskTag clear">In scope</span></div>`).join('')+(files.length>16?`<div class="emptyState">${files.length-16} additional files are included in this local scan.</div>`:'');});
  scanButton.addEventListener('click',async()=>{const overlay=document.querySelector('.loaderOverlay');overlay?.classList.add('show');const findings=[];for(const file of files){const text=await file.text();for(const rule of rules){if(rule.pattern.test(text)){const line=text.slice(0,text.search(rule.pattern)).split('\n').length;findings.push({...rule,file:file.webkitRelativePath||file.name,line});}}}const report={repository:input.files[0]?.webkitRelativePath.split('/')[0]||'Local repository',fileCount:files.length,scannedAt:new Date().toISOString(),findings};localStorage.setItem('aegisLocalReview',JSON.stringify(report));setTimeout(()=>{overlay?.classList.remove('show');results.hidden=false;findingTitle.textContent=`${findings.length} findings from ${files.length} local files.`;findingList.innerHTML=findings.length?findings.map((finding)=>`<div class="reviewRow"><span class="reviewIcon amber">!</span><div><b>${escape(finding.title)}</b><small>${escape(finding.file)} · line ${finding.line} · ${escape(finding.fix)}</small></div><span class="riskTag ${finding.severity==='Elevated'?'elevated':'review'}">${finding.severity}</span></div>`).join(''):'<div class="emptyState">No rule matches were found. This local scan checks a focused set of high confidence patterns.</div>';results.scrollIntoView({behavior:'smooth'});},450);});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initializeRepository);else initializeRepository();
